server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://noticias-db:5432/noticias_db}
spring.datasource.username=admin-noticias
spring.datasource.password=noticias006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
