server.port=8080
server.servlet.context-path=/noticias

# URL base API de datos (apiDatos)
api.noticias.url=${API_NOTICIAS_URL:http://localhost:8081}


# JWT expiracion
jwt.expiracionMs=3600000

# Frontend para CORS
frontend.url=http://localhost:8080

# JavaMail - Configuración para Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=antoniowebserver@gmail.com
spring.mail.password=mdkoqippnhddrleq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
